// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzWKEgTCT4F_YJr2O99dfA7vurIF8b2OY',
    appId: '1:770147629175:web:82026f3991759e4b62ee72',
    messagingSenderId: '770147629175',
    projectId: 'easyshop-111',
    authDomain: 'easyshop-111.firebaseapp.com',
    storageBucket: 'easyshop-111.firebasestorage.app',
    measurementId: 'G-4L3Z2Z0MQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRkWRgbjTm-NUR3nHNNDN8o2S5vMWDe9Y',
    appId: '1:770147629175:android:051d50ded08f1b8162ee72',
    messagingSenderId: '770147629175',
    projectId: 'easyshop-111',
    storageBucket: 'easyshop-111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Xd48eCLwa3ctpULljs__zEXIa1RwykE',
    appId: '1:770147629175:ios:56b8604fc1cc990962ee72',
    messagingSenderId: '770147629175',
    projectId: 'easyshop-111',
    storageBucket: 'easyshop-111.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Xd48eCLwa3ctpULljs__zEXIa1RwykE',
    appId: '1:770147629175:ios:56b8604fc1cc990962ee72',
    messagingSenderId: '770147629175',
    projectId: 'easyshop-111',
    storageBucket: 'easyshop-111.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzWKEgTCT4F_YJr2O99dfA7vurIF8b2OY',
    appId: '1:770147629175:web:72d8e88be6875a7d62ee72',
    messagingSenderId: '770147629175',
    projectId: 'easyshop-111',
    authDomain: 'easyshop-111.firebaseapp.com',
    storageBucket: 'easyshop-111.firebasestorage.app',
    measurementId: 'G-8Q5Y8QL6J2',
  );
}
